version: '3.8'

services:
  app_srv:
    hostname: ystuty-access-auth-provider
    build:
      context: .
      target: base
      dockerfile: ./Dockerfile
    command: yarn start:prod
    ports:
      # 8080 is the default port
      - ${EXTERNAL_PORT:-7471}:${SERVER_PORT:-8080}
    networks:
      - ystuty-access-network
    volumes:
      - ./.env:/home/node/app/.env
    healthcheck:
      test: curl --fail http://localhost:${SERVER_PORT:-8080}/api/app/uptime || exit 1
      interval: 2m
      retries: 3
      start_period: 40s
      timeout: 10s
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t

networks:
  ystuty-access-network:
    name: ystuty_access
    driver: bridge
